{
 "title": "Infra - RabbitMQ",
 "tags": [
  "infra",
  "rabbitmq",
  "poc"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rabbitmq_queue_depth_ratio", "legendFormat": "{{queue_name}}" }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rabbitmq_active_connections_ratio",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "Publish vs Consume (rate/min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (queue_name) (rate(rabbitmq_messages_published_total[1m])) * 60",
     "legendFormat": "pub:{{queue_name}}"
    },
    {
     "expr": "sum by (queue_name) (rate(rabbitmq_messages_consumed_total[1m])) * 60",
     "legendFormat": "con:{{queue_name}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{service_name=\"rabbitmq\"}"
    }
   ]
  }
 ]
}